require "roarify"
require "minitest/autorun"
require "pp"
require "representable/debug"
require "representer/product_representer"
require "representer/product_decorator"
require "representer/variant_decorator"
require "representer/search_representer"
require "product"
require "search"
require "shop"
require "request"
require "variant"

require "dummy/dummy_store"
require "dummy/dummy_data"

